name: Beta releases

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Install dependencies
        run: dotnet restore "AUCapture-WPF\AUCapture-WPF.csproj"

      - name: Publish
        run: |
          dotnet publish "AUCapture-WPF\AUCapture-WPF.csproj" -p:PublishProfile=DevProfile -p:AssemblyVersion=${{ steps.previoustag.outputs.tag }}.1

      - name: Relocate
        run: |
          mv AUCapture-WPF\\bin\\Release\\netcoreapp3.1\\publish\\AUCapture-WPF.exe ..\AmongUsCapture-Beta.exe

      - name: Zip
        run: |
          7z a AmongUsCapture-Beta.zip ..\AmongUsCapture-Beta.exe -mx=9
      
      - name: Sign
        uses: carbonneuron/openpgp-action@v1
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        id: sign
        with:
          path: ./AmongUsCapture-Beta.zip
          key: ${{ secrets.PRIVATE_KEY }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Output Signature
        shell: bash
        run: |
          echo "${{ steps.sign.outputs.encrypted-text }}" > AmongUsCapture-Beta.zip.sig

      - name: AmongUsCapture-beta
        uses: actions/upload-artifact@v2
        with:
          name: AmongUsCapture-beta
          path: AmongUsCapture-Beta.zip

      - name: Upload the signature
        uses: actions/upload-artifact@v1
        with:
          name: AmongUsCapture-Beta.sig
          path: AmongUsCapture-Beta.zip.sig
